version: "3.8"
services:
  app:
    build:
      context: .              
      dockerfile: Dockerfile  
      target: production-dependencies-env 
    container_name: myapp
    ports:
      - "3000:3000"           
    env_file:
      - .env                  
    volumes:
      - .:/app                
    command: ["pnpm", "run", "start"]  
