name: Generate PSI report
on:
  schedule:
    # https://crontab.guru/#30_2_*_*_0,1,2,3,4,5
    # At 02:30 on Sunday, Monday, Tuesday, Wednesday, Thursday, and Friday.
    - cron: "30 2 * * 0,1,2,3,4,5"

jobs:
  run_psi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: psi-gh-action
        uses: mazipan/psi-gh-action@1.5.0
        with:
          api_key: ${{ secrets.PSI_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          urls: |
            https://adibfirman.space/
            https://adibfirman.space/blog/
            https://adibfirman.space/blog/memahami-apa-itu-snowpack
          devices: |
            mobile
            desktop
          runs: 1
          max: 10
          override: false
          push_back: true
